### ISSUE TITLE
Questions regards Unity build

### ISSUE THREAD

**Issue by PotterDai** [neuecc/MagicOnion#10]
Hey, really excited for this project!
Got several questions while testing out with Unity3D.
Wondering how to get "grpc_csharp_ext" native library work on iOS and Android. Since gRPC official c# native plugin only support win/linux/mac platform.

Thank you very much! =)

**Comment by neuecc** [comment]
Our company has been built C Core library for iOS/Android myself.
https://github.com/grani/grpc/tree/UnityClient
I'll include binaries on this project.

**Comment by PotterDai** [comment]
That's amazing. Thank you very much! = )
