### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by Wulfklaue** [neuecc/MagicOnion#19]
Is MagicOnion technically not able to run on  .NET Core ( or the 2.0 beta )?

**Comment by neuecc** [comment]
Currently no.
But I'm planning to move the project to Visual Studio 2017 soon.
At that time, it may be made as a netstandard 1.5(includes .NET Core) project.

**Comment by PotterDai** [comment]
Hey @neuecc, is this still true?

**Comment by neuecc** [comment]
It is still the .NET Framework.
I have to make many modifications around reflection.
Please wait until the beginning of next month because I need a little time.

**Comment by neuecc** [comment]
I've released 0.5.0 and it supports .NET Core.
