### ISSUE TITLE
Intended exception in a sandbox code?

### ISSUE THREAD

**Issue by enigmatico** [neuecc/MagicOnion#26]
Not a significant thing, just for some curiosity...

https://github.com/neuecc/MagicOnion/blob/master/sandbox/Sandbox.ConsoleServer/Services/MyFirstService.cs#L14

If it is a intended behaviour, shouldn't sandbox sample client handle the exception from this status code?

Btw, It's really impressive work! I'd love to see it grow further. I'm going to play around the framework for some serious potential.

**Comment by neuecc** [comment]
Thank you for your interest!

Ah, sorry, this is the test code,  I've removed.
