### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by wahmedswl** [neuecc/MagicOnion#51]
Hi,
    Whats the preferred way to host Server? Can IIS be used to host MagicOnion Server or whats the preferred way.

Thanks

**Comment by neuecc** [comment]
This is following to standard gRPC system.
I'm using Windows Service with Topshelf.
gRPC contains HTTP/2 server and host by gRPC self so can not host on IIS.

**Comment by wahmedswl** [comment]
Thanks, that will help 👍
