### ISSUE TITLE
Freeze on Debug in VS

### ISSUE THREAD

**Issue by Rurouni** [neuecc/MagicOnion#52]
Hi,

We have an issue with constant Unity freezes when you attach VS debugger.
I was wondering if that commit [neucc/grpc](https://github.com/neuecc/grpc/commit/eb4b4fdb7fa60e0b76af9a0fbb866527328492fb ) fixes it?
Would it be possible for you please to update native binaries inside thise repo with the fixed version?

Thank you

**Comment by Rurouni** [comment]
My bad, we figured out that it was because we were not setting `GrpcEnvironment.IsDebugging = true;`
Feel free to close this issue but it would be great if you can tell some details on why it hangs and what's purpose of that magic delegate that is passed into the native and also why it need to have sleep of 10ms

**Comment by neuecc** [comment]
We do not understand completely yet.
Magic is truly magic, in the Japanese programming term, there are called `omajinai`.
